import Anthropic from '@anthropic-ai/sdk'
import { NextRequest, NextResponse } from 'next/server'

const anthropic = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY!,
})

const RATE_LIMIT_MAX = 10
const RATE_LIMIT_WINDOW_MS = 60 * 60 * 1000 // 1 hour

const ipRequestMap = new Map<string, { count: number; resetTime: number }>()

function getClientIp(request: NextRequest): string {
  return (
    request.headers.get('x-forwarded-for')?.split(',')[0].trim() ||
    request.headers.get('x-real-ip') ||
    'unknown'
  )
}

function checkRateLimit(ip: string): boolean {
  const now = Date.now()

  // Clean up expired entries
  for (const [key, entry] of ipRequestMap) {
    if (now > entry.resetTime) ipRequestMap.delete(key)
  }

  const entry = ipRequestMap.get(ip)
  if (!entry || now > entry.resetTime) {
    ipRequestMap.set(ip, { count: 1, resetTime: now + RATE_LIMIT_WINDOW_MS })
    return true
  }

  if (entry.count >= RATE_LIMIT_MAX) return false

  entry.count++
  return true
}

export async function POST(request: NextRequest) {
  const ip = getClientIp(request)
  if (!checkRateLimit(ip)) {
    return NextResponse.json(
      { error: 'Too many requests. Please try again later.' },
      { status: 429 }
    )
  }

  try {
    const body = await request.json()
    const { results, firstName, lang = 'en' } = body

    if (!results || results.length === 0) {
      return NextResponse.json({ error: 'No results provided' }, { status: 400 })
    }

    const isCzech = lang === 'cs'

    const scoreSummary = results.map((trait: {
      domain: string
      title: string
      score: number
      count: number
      shortDescription: string
    }) => {
      const percent = Math.round((trait.score / (trait.count * 5)) * 100)
      return `- ${trait.title} (${trait.domain}): ${percent}/100 — ${trait.shortDescription}`
    }).join('\n')

    const prompt = isCzech
      ? buildCzechPrompt(firstName, scoreSummary)
      : buildEnglishPrompt(firstName, scoreSummary)

    const system = isCzech
      ? 'Write your entire personality interpretation in Czech (čeština). Use natural, fluent Czech throughout. Do not mix in English.'
      : undefined

    const message = await anthropic.messages.create({
      model: 'claude-sonnet-4-6',
      max_tokens: 4096,
      ...(system ? { system } : {}),
      messages: [{ role: 'user', content: prompt }],
    })

    const evaluation = message.content[0].type === 'text' ? message.content[0].text : ''

    return NextResponse.json({ evaluation })
  } catch (err) {
    console.error('AI evaluation error:', err)
    return NextResponse.json({ error: 'Failed to generate evaluation' }, { status: 500 })
  }
}

function buildEnglishPrompt(firstName: string | null, scoreSummary: string): string {
  const name = firstName ? `The person's name is ${firstName}.` : 'The person completed the test anonymously.'
  return `You are an expert occupational psychologist specialising in the Big Five (OCEAN) personality model. You have just received the results of a scientifically validated IPIP-NEO-PI assessment.

${name}

Here are their Big Five scores:
${scoreSummary}

Write a personalised, insightful behavioural interpretation of these results. Structure your response in exactly four sections:

**Overview**
A 2-3 sentence summary of the overall personality profile and how the traits interact with each other.

**Strengths**
3-4 specific strengths that emerge from this particular combination of scores. Be concrete and behavioural — not generic.

**Potential Blind Spots**
2-3 areas where this personality profile may create challenges or blind spots. Be honest but constructive.

**Growth Areas**
2-3 actionable suggestions for personal or professional development based on these specific scores.

Important guidelines:
- Reference specific scores (e.g. "Your high Extraversion score of 65 suggests...")
- Be warm, professional, and constructive in tone
- Avoid generic statements that could apply to anyone
- Do not make clinical diagnoses or medical claims
- Use simple hyphens (-) instead of em dashes (—) or en dashes (–). Write in a natural, conversational tone as if a human typed it — avoid typographic flourishes.
- Total length: 400-600 words
- End with a single sentence disclaimer in italics: *This interpretation is generated by AI based on your assessment scores and is intended for self-reflection only — it is not a clinical assessment or professional psychological evaluation.*`
}

function buildCzechPrompt(firstName: string | null, scoreSummary: string): string {
  const name = firstName
    ? `Jméno osoby je ${firstName}.`
    : 'Osoba absolvovala test anonymně.'
  return `Jste expertní pracovní psycholog specializující se na model Velké pětky (OCEAN). Právě jste obdrželi výsledky vědecky ověřeného hodnocení IPIP-NEO-PI.

${name}

Zde jsou skóre Velké pětky:
${scoreSummary}

Napište personalizovanou, poučnou behaviorální interpretaci těchto výsledků. Strukturujte svou odpověď do čtyř sekcí:

**Přehled**
Shrnutí celkového osobnostního profilu v 2–3 větách a vzájemné interakce rysů.

**Silné stránky**
3–4 konkrétní silné stránky vyplývající z této kombinace skóre. Buďte konkrétní a behaviorální — vyhněte se obecnostem.

**Slepá místa**
2–3 oblasti, kde může tento osobnostní profil způsobovat problémy nebo slepá místa. Buďte upřímní, ale konstruktivní.

**Oblasti rozvoje**
2–3 realizovatelné návrhy pro osobní nebo profesní rozvoj na základě těchto konkrétních skórů.

Důležité pokyny:
- Odkazujte na konkrétní skóre (např. „Vaše vysoké skóre Extraverze 65 naznačuje...")
- Buďte vřelí, profesionální a konstruktivní v tónu
- Vyhněte se obecným tvrzením platným pro kohokoli
- Nevyslovujte klinické diagnózy ani zdravotní tvrzení
- Používejte jednoduché pomlčky (-) místo em pomlček (—) nebo en pomlček (–). Pište přirozeným, konverzačním tónem — vyhněte se typografickým ozdobám.
- Celková délka: 400–600 slov
- Zakončete jednou větou v kurzívě: *Tato interpretace je generována umělou inteligencí na základě výsledků vašeho hodnocení a je určena pouze k sebereflexexi — nejedná se o klinické posouzení ani odborné psychologické hodnocení.*`
}
