import Anthropic from '@anthropic-ai/sdk'
import { NextRequest, NextResponse } from 'next/server'

const anthropic = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY!,
})

export async function POST(request: NextRequest) {
  try {
    const body = await request.json()
    const { results, firstName } = body

    if (!results || results.length === 0) {
      return NextResponse.json({ error: 'No results provided' }, { status: 400 })
    }

    // Build the score summary for the prompt
    const scoreSummary = results.map((trait: {
      domain: string
      title: string
      score: number
      count: number
      shortDescription: string
    }) => {
      const percent = Math.round((trait.score / (trait.count * 5)) * 100)
      return `- ${trait.title} (${trait.domain}): ${percent}/100 — ${trait.shortDescription}`
    }).join('\n')

    const name = firstName ? `The person's name is ${firstName}.` : 'The person completed the test anonymously.'

    const prompt = `You are an expert occupational psychologist specialising in the Big Five (OCEAN) personality model. You have just received the results of a scientifically validated IPIP-NEO-PI assessment.

${name}

Here are their Big Five scores:
${scoreSummary}

Write a personalised, insightful behavioural interpretation of these results. Structure your response in exactly four sections:

**Overview**
A 2-3 sentence summary of the overall personality profile and how the traits interact with each other.

**Strengths**
3-4 specific strengths that emerge from this particular combination of scores. Be concrete and behavioural — not generic.

**Potential Blind Spots**
2-3 areas where this personality profile may create challenges or blind spots. Be honest but constructive.

**Growth Areas**
2-3 actionable suggestions for personal or professional development based on these specific scores.

Important guidelines:
- Reference specific scores (e.g. "Your high Extraversion score of 65 suggests...")
- Be warm, professional, and constructive in tone
- Avoid generic statements that could apply to anyone
- Do not make clinical diagnoses or medical claims
- Total length: 400-600 words
- End with a single sentence disclaimer in italics: *This interpretation is generated by AI based on your assessment scores and is intended for self-reflection only — it is not a clinical assessment or professional psychological evaluation.*`

    const message = await anthropic.messages.create({
      model: 'claude-sonnet-4-6',
      max_tokens: 1024,
      messages: [{ role: 'user', content: prompt }],
    })

    const evaluation = message.content[0].type === 'text' ? message.content[0].text : ''

    return NextResponse.json({ evaluation })
  } catch (err) {
    console.error('AI evaluation error:', err)
    return NextResponse.json({ error: 'Failed to generate evaluation' }, { status: 500 })
  }
}